config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    path: :gurus, 
    path_names: { sign_in: :login, sign_out: :logout }

  root to: 'tests#index'

  delete :signout, to: 'sessions#destroy'

  resources :tests, only: :index, shallow: true do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get 'result', on: :member
    post :gist, on: :member
  end

  namespace :admin do
    root to: 'tests#index'

    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end

  resources :feedback, only: [:new, :create]

end

app/views/shared/_admin_navigation.html.slim
header.navbar.navbar-expand.navbar-dark.flex-column.flex-md-row.bd-navbar
  = link_to t('application.title').mb_chars.capitalize.to_s, 
    root_path, 
    class: 'navbar-brand mr-0 mr-md-2'
  - if user_signed_in?
    .navbar-nav-scroll
      .navbar-nav.bd-navbar-nav.flex-row
        li.nav-item
          = link_to 'Gists', admin_gists_path, class: 'nav-link'
        li.nav-item
          = link_to 'Test', admin_tests_path, class: 'nav-link'

  .navbar-nav-scroll.ml-md-auto
    ul.navbar-nav.bd-navbar-nav.flex-row 
      - if user_signed_in?
        li.nav-item.nav-link #{ t('application.welcome' ).mb_chars.capitalize.to_s }, 
          #{ current_user.email } 
          [ #{ link_to t('application.exit' ), destroy_user_session_path, method: :delete } ]
      - else
        li.nav-item
          = link_to t('.signup'), 
            new_user_registration_path, 
            class: 'nav-link'
        li.nav-item
          = link_to t('.signin'), 
            new_user_session_path,
            class: 'nav-link'

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.present?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do
    strong #{ t('.error', count: resource.errors.count) }

    ul 
      - resource.errors.full_messages.each do |error|
        li = error

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  = content_tag :div,  message.html_safe, class: "alert #{ flash_class(key.to_sym) }"

app/views/shared/_footer.html.slim
footer.footer
  .container
    = current_year
    | &nbsp; | &nbsp;
    | #{link_to 'Maksim R',   github_url('Rukomoynikov', 'thinknetica-testguru'),  target: :blank}
    | &nbsp; | &nbsp;
    | #{link_to 'TestGuru', 'https://github.com/Rukomoynikov/thinknetica-testguru', target: :blank}
    | &nbsp; | &nbsp;
    | #{link_to 'Учебный проект в онлайн-школе Thinknetica',  'https://thinknetica.com', target: :blank}

app/views/shared/_navigation.html.slim
header.navbar.navbar-expand.navbar-dark.flex-column.flex-md-row.bd-navbar
  = link_to t('application.title').mb_chars.capitalize.to_s, 
    root_path, 
    class: 'navbar-brand mr-0 mr-md-2'
  .navbar-nav-scroll.ml-md-auto
    ul.navbar-nav.bd-navbar-nav.flex-row 
      - if user_signed_in?
        li.nav-item.nav-link #{ t('application.welcome' ).mb_chars.capitalize.to_s }, 
          #{ current_user.email } 
          [ #{ link_to t('application.exit' ), destroy_user_session_path, method: :delete } ]
      - else
        li.nav-item
          = link_to t('.signup'), 
            new_user_registration_path, 
            class: 'nav-link'
        li.nav-item
          = link_to t('.signin'), 
            new_user_session_path,
            class: 'nav-link'