config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    path: :gurus, 
    path_names: { sign_in: :login, sign_out: :logout }

  root to: 'tests#index'

  delete :signout, to: 'sessions#destroy'

  resources :tests, only: :index, shallow: true do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get 'result', on: :member
    post :gist, on: :member
  end

  namespace :admin do
    root to: 'tests#index'

    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end

  resources :feedback, only: [:new, :create]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, 
            :question_id,
            presence: true

  scope :correct, -> { where correct: true }

  validate :validate_answers_in_question_count

  def validate_answers_in_question_count
    errors.add(:question, 'Already filled with answers') if self.question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: [:new]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)

    if @answer.save
      redirect_to admin_question_path(@answer.question), notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy

    redirect_to @answer.question
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body, :question_id, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.slim
li
  div = answer.body
  div 
    = link_to 'Show', admin_answer_path(answer)
    |  |  
    = link_to 'Edit', edit_admin_answer_path(answer)
    |  | 
    = link_to 'Delete', admin_answer_path(answer), method: :delete

app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer ], local: true) do |form| %>
  <%= form.hidden_field :question_id %>

  <p>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct %>
  </p>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/admin/answers/edit.html.slim
h1 = t('.title')

= render 'form', answer: @answer

= link_to 'Show', [:admin, @answer]
| |
= link_to 'Back', [:admin, @answer.question]

app/views/admin/answers/new.html.slim
h1 = t('.title')

p = @answer.question.body

= render 'form', answer: @answer

= link_to 'Back', admin_question_path(@answer.question)

app/views/admin/answers/show.html.slim
h1 Question

p = @answer.question.body

p
  b Answer:
  =  @answer.body

p 
  b Correct:
  =  @answer.correct


= link_to 'Back', question_path(@answer.question)