config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    path: :gurus, 
    path_names: { sign_in: :login, sign_out: :logout }

  root to: 'tests#index'

  delete :signout, to: 'sessions#destroy'

  resources :tests, only: :index, shallow: true do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get 'result', on: :member
    post :gist, on: :member
  end

  namespace :admin do
    root to: 'tests#index'

    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end

  resources :feedback, only: [:new, :create]

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, 
            :test_id,
            presence: true

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :set_test, only: [:new, :create]
  before_action :set_question, only: [:show, :delete, :edit]

  rescue_from ActiveRecord::RecordNotFound, 
              with: :rescue_with_question_not_found

  def new; 
    @question = Question.new
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_path(@test)
    else 
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update question_params
      redirect_to admin_test_path(@question.test)
    else 
      render :edit
    end
  end

  def show; end

  def destroy
    @question.destroy

    redirect_to test_path(@test)
  end

  private 

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден'
  end
end

app/helpers/question_helper.rb
module QuestionHelper
  def question_form_title(record, title)
    if record.persisted?
      "Edit question for test #{ title }"      
    else
      "Create new question for test #{ title }"      
    end
  end
end

app/views/admin/questions/_buttons.html.slim
/ = link_to 'Show ', admin_question_path(@question) if action_name == 'edit'

/ = link_to 'Edit ', edit_admin_question_path(@question) if action_name == 'show'

= link_to '< Questions List ', edit_admin_question_path(@question) if action_name == 'show'

app/views/admin/questions/_form.html.slim
= form_with model: [:admin, @test, @question], local: true do |f|
  = hidden_field_tag 'question[test_id]', params[:test_id] || @question.test.id

  / = @question.errors.full_messages
  = render 'shared/errors', resource: @question

  p 
    = f.label :body
    = f.text_field :body
  p 
    = f.submit

app/views/admin/questions/edit.html.slim
h1 = t('.title', test: @question.test.title)

= render 'form'

= render 'buttons'

app/views/admin/questions/new.html.slim
h1 = t('.title', test: @test.title)

= render 'form'

= render 'buttons'

app/views/admin/questions/show.html.slim
h1 #{ t('.title') }: #{ @question.body } (#{ link_to t('.add_answer'), new_admin_question_answer_path(@question) })

p #{ t('.answers_list') }:

ol
  = render @question.answers

= render 'buttons'