config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    path: :gurus, 
    path_names: { sign_in: :login, sign_out: :logout }

  root to: 'tests#index'

  delete :signout, to: 'sessions#destroy'

  resources :tests, only: :index, shallow: true do
    post :start, on: :member
  end

  resources :test_passages, only: [:show, :update] do
    get 'result', on: :member
    post :gist, on: :member
  end

  namespace :admin do
    root to: 'tests#index'

    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member

      resources :questions, except: :index do
        resources :answers, except: :index
      end
    end
  end

  resources :feedback, only: [:new, :create]

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def new
  end

  def create
    FeedbackMailer.simple(feedback_params).deliver_now!

    flash[:notice] = t('.message_sent')
    
    redirect_to new_feedback_path
  end

  private

  def feedback_params
    params.permit(:sender_name, :feedback_body)
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/new.html.slim
.container
  h1 = t('.title')

  = form_with url: feedback_index_path, method: :post, local: true do |form|

    .form-group
      = form.label :sender_name, t('.sender_name')
      = form.text_field :sender_name, class: 'form-control', required: true

    .form-group
      = form.label :feedback_body, t('.feedback_body')
      = form.text_area :feedback_body, class: 'form-control', required: true

    .form-group
      = form.submit t('.submit')